### ISSUE TITLE
Optimize History Page

### ISSUE THREAD

**Issue by kaytsui** [icr-ctl/scrubdash#1]
# Task

Optimize grid rendering

- [x] Layout
  - [x] Images are rendered in "pages" in a 3x3 grid layout.
  - [x] `Next` and `Back` buttons should be displayed if there are more images to go through or previous images respectively.
- [x] Modal View
  - [x] A modal component pops up when a user clicks on an image
  - [x] The modal component displays the confidence slider and image they just clicked on.
    - [x] Changing the value on the confidence slider updates the lboxes drawn on the image.

These optimizations allow less images to be displayed at a time and allows the server to draw lboxes on only one image at a time, which reduces the amount of bytes that need to be read from disk.
